Ruby on Rails: Associations
edxco/PrivateEvents pull request #1
Opened 2020-12-05 18:38 UTC by mke2111

For this project, we:-

- Created user, event, and attendee models and controllers.
- Added many to many relationships amongst user, event, and attendee which are attended_events and user_attendee.
- Implemented a lightweight authentication feature.
- Created views to display events and users.

2020-12-05 20:02 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 the design is 🤯 you still need to make some changes though! 

## Required Changes ♻️ 

- [x] when I create a user, I get an error in Users#Show, the reason is you're looking for an event using the id params, and I don't have any events _yet_ so it will make that error, remove the `@event` variable to fix this.

- [x] when creating an event, it redirects me to Events#Show and i get an error because you wrote `Attendance.new` instead of `Attendee.new`

- [x] trying to join an event gives me this error page whenever i try to load to the user's page again: 
![image](https://user-images.githubusercontent.com/11758151/101261974-4da21c80-373b-11eb-908c-ed01e142f638.png)

the reason is you're using `@event` (which i deleted to solve the problem, instead you need to use `event` that you have in `@created_events.each do |event|`

- [x] the `home` and `my events` links are not working, and have `#` as the link ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/navigation_links_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

- [x] use `foreign_key` and `class_name` in your models
  * [x] User model: `has_many :events, foreign_key: :creator_id` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
  * [ ] Event model `belongs_to :creator, class_name: "User"` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
  - [ ] events table has creator_id as the foreign key ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

* [ ] authentication should have has integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))
* [ ] event managment features should have integration tests (Rspec + Capybara) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/integration_tests_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49723079/))


### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-12-05 22:14 UTC, elmejdki requested changes
# status: require changes :recycle: 

Great job so far @team :+1:, supper cool design though I really liked it :100: :1st_place_medal: . You still have some changes :hammer: :wrench: :toolbox: to take care of in order to get this project approved :checkered_flag:.

## Required Changes:

- [ ] if a user tries to attend the event multiple times, it will duplicate his name on the attendee's list. please hide the I will assist button for users that are already registered, or come up with another solution for it.

![image](https://user-images.githubusercontent.com/34653764/101266319-01aca300-374e-11eb-93c3-6e10840feb5f.png)

here we can see user `test2` is duplicated

- [ ] Please add integration tests as mentioned by the previous TSE

- [ ] you have some tests failing please fix them:
![image](https://user-images.githubusercontent.com/34653764/101266402-c78fd100-374e-11eb-9577-2db2736ccc0e.png)

- [ ] The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming:
![image](https://user-images.githubusercontent.com/34653764/101266429-163d6b00-374f-11eb-9845-2e7d9b1c7981.png)

- [ ] add the link that redirects to the users show page the only way that I was able to access this page is using the URL.

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have any questions don't hesitate to contact me on slack._

2020-12-05 22:14 UTC, elmejdki commented on app/controllers/users_controller.rb
> +    @event = Event.find(params[:id])
- [ ] how come the user and event have the same ID??, when I try to create a new user an error occur marking this page check the image below:

![image](https://user-images.githubusercontent.com/34653764/101266228-366c2a80-374d-11eb-932e-a7dd8314cf39.png)

remove the @event variable as mentioned by the previous TSE.

2020-12-08 05:06 UTC, javitocor requested changes
# STATUS CHANGES REQUIRED ♻️ 

Wow, team, an amazing job so far! Really like your design! 👍 
However, there are some requested changes by previous TSE that have not been implemented yet! Let's go with them! 💪 
Once the changes are done, resubmit your project for a new code review ⏩ 
Good luck with it! 😄 
## Mandatory changes
- Add integration test for all the different features, attend and event, unattended an event, login, signup, create event...
- Also unit tests to test models validations
- Also fix the tests that are failing
- The users are still duplicates when accessing multiple times to an event, kindly fix it.

2020-12-08 17:05 UTC, edxco commented
Fixed the following:

- A user can't attend twice to the same event
- Add rspec tests

2020-12-08 17:45 UTC, lekegitrepo requested changes
## Status: Changes Required :recycle:
#### Hi @mke2111 and @edxco :clap: :clap:
#### Good job so far :+1: I know that you are working hard and doing your best to implement the required changes in order to get this project approved, just keep learning and don't be discouraged about the reviews.
#### Some of the required changes mentioned in the previous review are still missing. Check my comments below :point_down:

#### Tests:
- **_The integration tests are still missing [check this link](https://www.codewithjason.com/rails-integration-tests-rspec-capybara/) and [this one](https://thoughtbot.com/blog/rspec-integration-tests-with-capybara) and [this](https://www.microverse.org/blog/understanding-rspec-controller-request-specs-integration-test-using-capybara) to learn more about how to write integration tests. Add tests for all the different features, attend and event, unattended an event, login, signup, create event_**

- **_test the association between models(this is not hard you can add `shoulda` gem to make the association test easier)_**

#### _Reviewed by Temitayo Adeleke_

2020-12-09 01:38 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

## Great job @mke2111 :clap: :clap: :clap: :clap:, thanks for making the required changes :100: :+1:.

now you can merge to develop your project is approved.

## Happy Coding :tophat:

2020-12-09 05:26 UTC, merged